/**
 * Horizon Bank – Dashboard SQL Execution Route
 * POST /api/dashboard
 *
 * Receives an array of chart specs (generated by the LLM) and executes each
 * SQL statement safely against Supabase.  Only SELECT statements are allowed.
 *
 * Request body:
 * {
 *   charts: [
 *     { title: "KPI Overview", type: "bar", sql: "SELECT kpi_name, current_value FROM ..." }
 *   ]
 * }
 *
 * Response:
 * {
 *   charts: [
 *     { title: "KPI Overview", type: "bar", data: [...rows] }
 *   ]
 * }
 *
 * Security:
 *  - Only SELECT statements are executed (DDL / DML is rejected).
 *  - Queries are limited to 500 rows to avoid runaway responses.
 *  - Only the `data_records` table is accessible via SQL (enforced by RLS +
 *    allow-list check on the table name referenced in the query).
 */

import { createClient, SupabaseClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";

export const runtime = "nodejs";

// ─── Types ────────────────────────────────────────────────────────────────────

interface ChartSpec {
  title: string;
  type: "bar" | "line" | "pie" | "table";
  sql: string;
}

interface ChartResult {
  title: string;
  type: string;
  data?: Record<string, unknown>[];
  error?: string;
}

// ─── Security helpers ─────────────────────────────────────────────────────────

const FORBIDDEN_KEYWORDS = /\b(INSERT|UPDATE|DELETE|DROP|TRUNCATE|ALTER|CREATE|GRANT|REVOKE|EXECUTE|EXEC|CALL|COPY|VACUUM|REINDEX|CLUSTER|LOCK|COMMENT|SET|RESET)\b/i;

/** Gold tables that queries are allowed to reference. */
const ALLOWED_TABLES = ["gold_dim_kpi", "gold_dim_period", "gold_dim_team", "gold_fact_kpi", "data_records"];

function validateSql(sql: string): string | null {
  const trimmed = sql.trim();

  // Must be a SELECT statement
  if (!/^SELECT\b/i.test(trimmed)) {
    return "Only SELECT statements are permitted.";
  }

  // No forbidden DML/DDL keywords
  if (FORBIDDEN_KEYWORDS.test(trimmed)) {
    return "Statement contains forbidden keywords (only pure SELECT is allowed).";
  }

  // No semicolons allowed anywhere (SQL injection guard).
  // Strip a single trailing semicolon if present, then reject any remaining ones.
  const withoutTrailingSemi = trimmed.endsWith(";") ? trimmed.slice(0, -1) : trimmed;
  if (/;/.test(withoutTrailingSemi)) {
    return "Statement contains a semicolon – multiple statements are not allowed.";
  }

  // Must reference at least one allowed table (prevent queries to sensitive tables)
  const referencesAllowed = ALLOWED_TABLES.some((t) =>
    new RegExp(`\\b${t}\\b`, "i").test(trimmed)
  );
  if (!referencesAllowed) {
    return `Queries must reference one of: ${ALLOWED_TABLES.join(", ")}.`;
  }

  return null; // valid
}

// ─── Supabase query execution ─────────────────────────────────────────────────

async function runSelectQuery(
  supabase: SupabaseClient,
  sql: string
): Promise<Record<string, unknown>[]> {
  // Strip any trailing semicolon, then append a row cap if the LLM didn't add one.
  const stripped = sql.trimEnd().replace(/;$/, "");
  const cappedSql = /\bLIMIT\b/i.test(stripped) ? stripped : `${stripped} LIMIT 500`;

  // Supabase JS client doesn't support arbitrary SQL; we use the rpc escape hatch
  // by calling a helper function we create, or fall back to the REST /rest/v1/rpc.
  // Since we need raw SQL execution, we use the PostgREST rpc endpoint via fetch.
  const supabaseUrl = process.env.SUPABASE_URL!;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

  const res = await fetch(`${supabaseUrl}/rest/v1/rpc/execute_dashboard_query`, {
    method: "POST",
    headers: {
      apikey: serviceKey,
      Authorization: `Bearer ${serviceKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ query_sql: cappedSql }),
  });

  if (!res.ok) {
    const errText = await res.text();

    // If the RPC function doesn't exist yet, fall back to direct table queries
    // that the Supabase JS client can do without arbitrary SQL.
    if (res.status === 404 || errText.includes("does not exist")) {
      return await fallbackDirectQuery(supabase, cappedSql);
    }

    throw new Error(`Query failed (${res.status}): ${errText}`);
  }

  const rows = await res.json();
  return Array.isArray(rows) ? rows : [];
}

/**
 * Fallback when the execute_dashboard_query RPC doesn't exist yet.
 * Detects which gold table the query targets and performs a direct select.
 * Supports simple single-table queries; JOIN queries require the RPC to be set up.
 */
async function fallbackDirectQuery(
  supabase: SupabaseClient,
  sql: string
): Promise<Record<string, unknown>[]> {
  // Determine the target table (first gold/data table name found in the SQL)
  const ALLOWED = ["gold_dim_kpi", "gold_dim_period", "gold_dim_team", "gold_fact_kpi", "data_records"];
  let targetTable: string | null = null;
  for (const t of ALLOWED) {
    if (new RegExp(`\\b${t}\\b`, "i").test(sql)) {
      targetTable = t;
      break;
    }
  }

  if (!targetTable) {
    throw new Error("Could not determine target table from SQL for fallback query.");
  }

  const limitMatch = sql.match(/LIMIT\s+(\d+)/i);
  const limitVal = limitMatch ? parseInt(limitMatch[1], 10) : 500;

  if (targetTable === "data_records") {
    // Legacy path: extract table_name filter and unwrap row_data JSONB
    const tableNameMatch = sql.match(/table_name\s*=\s*'([^']+)'/i);
    const tableName = tableNameMatch ? tableNameMatch[1] : null;
    let query = supabase.from("data_records").select("row_data");
    if (tableName) query = query.eq("table_name", tableName);
    query = query.limit(limitVal);
    const { data, error } = await query;
    if (error) throw new Error(`Direct query failed: ${error.message}`);
    type DataRecordRow = { row_data: Record<string, unknown> };
    return ((data ?? []) as DataRecordRow[]).map((r) => r.row_data);
  }

  // Gold tables: direct select, all columns
  const { data, error } = await supabase
    .from(targetTable)
    .select("*")
    .limit(limitVal);

  if (error) throw new Error(`Direct query failed on ${targetTable}: ${error.message}`);
  return (data ?? []) as Record<string, unknown>[];
}

// ─── Route handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const supabaseUrl = process.env.SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceRoleKey) {
    return NextResponse.json(
      { error: "Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY" },
      { status: 500 }
    );
  }

  const supabase = createClient(supabaseUrl, serviceRoleKey);

  let body: { charts?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  if (!Array.isArray(body.charts) || body.charts.length === 0) {
    return NextResponse.json(
      { error: "Request body must include a non-empty `charts` array." },
      { status: 400 }
    );
  }

  if (body.charts.length > 10) {
    return NextResponse.json(
      { error: "Maximum 10 charts per request." },
      { status: 400 }
    );
  }

  const results: ChartResult[] = [];

  for (const spec of body.charts as ChartSpec[]) {
    if (
      typeof spec.title !== "string" ||
      typeof spec.type !== "string" ||
      typeof spec.sql !== "string"
    ) {
      results.push({
        title: String(spec?.title ?? "Untitled"),
        type: String(spec?.type ?? "table"),
        error: "Chart spec must have string fields: title, type, sql.",
      });
      continue;
    }

    const validationError = validateSql(spec.sql);
    if (validationError) {
      results.push({ title: spec.title, type: spec.type, error: validationError });
      continue;
    }

    try {
      const data = await runSelectQuery(supabase, spec.sql);
      results.push({ title: spec.title, type: spec.type, data });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      results.push({ title: spec.title, type: spec.type, error: message });
    }
  }

  return NextResponse.json({ charts: results });
}
